### ISSUE TITLE
How to deploy a dataset

### ISSUE THREAD

**Issue by Eezo20v** [mmajcica/DeploySsrs#2]
Hi Mario,
Can you please give me a sample on the xml required to deploy a shared dataset?
The shared datasets are already setup in my project as *.rsd.

Apologies if it's been mentioned elsewhere, I couldn't find any documentation on how to set it up.

I would imagine something along the lines of 
`<Folder Name="Datasets" Hidden="true">
      <Dataset Name="BusinessStream" FileName="BusinessStream.rsd" />
    </Folder>`

Ernest

**Comment by mmajcica** [comment]
Hi Ernest,

it should be pretty straight away:

```xml
<Folder>
    <DataSets>
        <DataSet Name="Dataset1" FileName="Dataset1.rsd" />
        <DataSet Name="Dataset2" Hidden="true" FileName="Dataset2.rsd" />
        <DataSet Name="Dataset3" FileName="Dataset3.rsd">
            <Security Name="Administrator">
              <Roles>
                <Role>Browser</Role>
                <Role>Content Manager</Role>
              </Roles>
            </Security>
          </Security>
        </DataSet>
        <DataSet Name="Dataset4" InheritParentSecurity="True" FileName="Dataset4.rsd" />
    </DataSets>
</Folder>
```
This example show all of the available options.
Also, this is the cmdlet that process the xml config file, thus you can always relate to the code in order to see all of the possibilities, https://github.com/mmajcica/DeploySsrs/blob/64bf1ba98c08ebf593c60cf6f523353b7e6aade1/task/ps_modules/ssrs.psm1#L534

Let me know how it went!

Cheers
