### ISSUE TITLE
Deploy reports error: error downloading asmx file

### ISSUE THREAD

**Issue by bbecher** [mmajcica/DeploySsrs#29]
When attempting to deploy reports, I am getting an error for the deploy phase of the process.

![image](https://user-images.githubusercontent.com/40467605/57298188-97c6a600-709f-11e9-97cf-c19caa406e1f.png)
I have confirmed that I am able to reach the ASMX endpoint manually with no issues.

The plugin is configured as follows:
![image](https://user-images.githubusercontent.com/40467605/57298326-ed02b780-709f-11e9-965d-5963ce123373.png)

Note: When attempting this with both WinAuth and SQL Server Auth, the same error results.

I have tried users with various permission settings with no change in results.

**Comment by sreeraj-rajendran** [comment]
@bbecher were you able to get past this?

I am not sure if I am right here, but from what I understood from the code, upon selected Windows authentication the account with which the build agent is running would be used to try and connect to the SSRS endpoint **(UseDefaultCredential** ) : 

$proxy = New-WebServiceProxy -Uri $url -Namespace SSRS.ReportingService2010 -UseDefaultCredential -Class "SSRS"

@mmajcica thanks for this extension, this would definitely help us.
We have just started using this, and had hit the same issue that @bbecher was running into.

**Can you please help with your thoughts on some of the observations:**

1. If we use SQL auth, we get a 401 as the credential for New-WebServiceProxy is being built based on that. I am not sure if we can authorize to SSRS using sql authentication. Wouldn't this need an account that has permission to SSRS itself rather than just the database?

$proxy = New-WebServiceProxy -Uri $url -Namespace SSRS.ReportingService2010 -Credential $credential -Class "SSRS"

Also with windows authentication it looks like we would be using the build agent's service account to connect to SSRS.

2. If the ReportService2010 endpoint URL is provided as in the description - http://your.server/ReportServer/ReportService2010.asmx?wsdl, Format-SsrsUrl would convert it to http://your.server/ReportServer/ReportService2010.asmx?wsdl/ReportService2010.asmx

I am not a developer myself, but I'll check if I can submit a PR if these seem valid.

**Comment by mmajcica** [comment]
Using Windows Authentication option will imply that the code sets the UseDefaultCredential property in the resulting proxy object to True. This also means that the calls we assume the identity of your build agent. It means that that account need to have sufficient permissions granted in SQL and SSRS.

Regarding the validation of the URL, the function expects that the provided URL ends up with .asmx. Just remove ?wsdl from your URL and you will not have issues anymore.

All of the authentications issues are not strictly related to this task, but to your SQL and infrastructure setup. If there are no issues with the task itself, I would like to close this thread and advise you to search for SQL and SSRS help in more indicated places.

**Comment by sreeraj-rajendran** [comment]
Thanks @mmajcica .

This was more of a usability suggestion, as the help text for **ReportService2010 endpoint URL** says,
: The Report Server Web service ReportService2010 endpoint URL. E.g. http://your.server/ReportServer/ReportService2010.asmx?wsdl - which would throw an error, and then we had to spend some time to find why this was happening :)

Similar was the help text for Authentication and Username / Password.
We are good now- Thanks!

**Comment by mmajcica** [comment]
If it really bothering you, it is a small change. Create an issue and I'll
make the change and publish it.

Cheers

**Comment by sreeraj-rajendran** [comment]
We are good now, thanks.
Sorry for hijacking the thread @bbecher 

Thanks!

**Comment by bbecher** [comment]
After reviewing the comments, and looking over the agent jobs I have resolved this.

The machine the agent was running on did not have access to our servers.

After resolving this, everything appears to work correctly.

**Comment by acds** [comment]
@mmajcica Thanks for maintaining this add-in.

It would be great to have a place with trouble shooting recommendations for this issue. I have remoted to the agent VM as the agent credentials and in a browser the ReportService2010 endpoint URL return the requisite wsdl, so it seems not to be a permisions issue.

I get ```2019-12-11T00:30:43.8580153Z ##[error]There was an error downloading 'https://<server>/AREIS_DEV_SSRS/ReportService2010.asmx'.```

Is there a way to turn on more verbose diagnostics.

**Comment by mmajcica** [comment]
Your account on that machine, is it the same as the account that is running
the agent? If so, from your build server, can you try to replicate what the
task is doing? Check the code and try to run a PS with a part of it under
the same identity that agent is running under.
