### ISSUE TITLE
Support for PBIRS requested; deployment of Power BI reports

### ISSUE THREAD

**Issue by q0-0n** [mmajcica/DeploySsrs#9]
The current DeploySsrs version does not fully support the features of the new Power BI Reporting Server.

Desired outcome;
Being able to deploy a Power BI report using DeploySsrs.

A possible solution could be the [Write-RsRestCatalogItem](https://github.com/Microsoft/ReportingServicesTools/blob/master/ReportingServicesTools/Functions/CatalogItems/Rest/Write-RsRestCatalogItem.ps1) function at [ReportingServicesTools](https://github.com/Microsoft/ReportingServicesTools) that can deploy PBI reports, KPI's and other binary files (such as Excel or images).

@mmajcica Would you be willing to give your view on this request? I would like to know how I can contribute to your project.

**Comment by mmajcica** [comment]
Hi,

I currently do not have time to focus on this nor I have experience with Power BI. If you can introduce this new functionalities, without breaking the current set of features, I'll be more then happy to assist with the review and publishing. To start, for the project, make your changes, test it and once done, make a PR. However, considering the size of this change, if you decide to contribute, I'll like to have a small 'refinement' session in order to make sure that all of the added does make sense and to lay down the requirements in a clean way.

Thanks
